### ISSUE TITLE
List view checkboxes - unable to select multiple items in list view, one by one.

### ISSUE THREAD

**Issue by paul-seal** [umco/umbraco-fluidity#11]
I can use select all or I can select one item, but I can't select more than one item by ticking the checkbox.
See attached gif.

![list-view-error](https://user-images.githubusercontent.com/33097387/34604306-27d82d7a-f1ff-11e7-94e7-da10ba394f9c.gif)

**Comment by mattbrailsford** [comment]
Fixed in commit 4377b4b 

Looks like the umbraco table directive needs a "key" property on an entity (which umbraco entities do). This key is compared with other selected items to see if an item is already selected. As all entities didn't have a key, these would be `undefined` and thus they are equal. 

I've added some code to generate a key guid based on the id so it should be uniqe by entity. This should do the trick.
