### ISSUE TITLE
Custom properties for collections

### ISSUE THREAD

**Issue by peterdremstrup** [umco/umbraco-fluidity#55]
Hi,

I'm in the process of integrating an external api service as a collection of collections, with the magic of Fluidity for interface stuff. I need to add some custom properties to the collection, so it knows the parameters of the request it needs to send (in this case an id of a "channel").
I've managed to hack a working solution together, where i use the alias of the collection to send the id to the custom repository.

How would you go about this? I'd be happy to contribute some code, so far I've just made the collection available to the repository, so I could access the alias, but I was thinking along the lines of adding a dictionary (string key, object value), that you can search through from the repository.

**Comment by mattbrailsford** [comment]
If I'm understanding you correctly, you want to link an entity from one collection to another entity in another collection?

If so, Fluidity does come with an Entity Picker property editor so you could configure a property editor to pick your parent entity. If this is a 1 to 1 relation it should be pretty straight forward. If it's many to many, you'd have to implement a custom repository to handle saving the value to a match table.

The thing with Fluidity, whenever you need something custom like this is to think in Property Editors. Because Fluidity uses property editors for the editing values, if one doesn't exist, you should be able to create a custom one the same way you would for umbraco and use it within Fluidity.

So, if my thought is correct, you may be able to use the Entity Picker, but if not, you could either create your own property editor to solve this, or maybe look and see what other property editors might help. For example, the nuPicker package allows you to create SQL data sources for a variety of different types of pickers, so you could use that and configure it with SQL statements accessing your DB tables.

Hope this helps

Matt

**Comment by peterdremstrup** [comment]
I'm trying to implement a custom repository, that doesn't use SQL, but another C#-package which interfaces with an external api we're using for podcasts.

So what I've done is implemented a custom repository, that just uses the external API in the different methods. But that repository needs a channel id, to request episodes from that specific channel.

![billede](https://user-images.githubusercontent.com/1673937/41100579-107024f4-6a62-11e8-9c9c-948f9fcf805d.png)

**Comment by peterdremstrup** [comment]
All I've done to get that working is changing the `_alias` property in [FluidityTreeItemConfig.cs](https://github.com/umco/umbraco-fluidity/blob/develop/src/Fluidity/Configuration/FluidityTreeItemConfig.cs) to a public property, and then I'm always sending the collection into the Repository, instead of only the defaultrepository.

**Comment by mattbrailsford** [comment]
Ok, first off, you shouldn't need to make `_alias` public, there should be a `SetAlias` method you can call.

But I think I get what you are doing now, although I hadn't thought of using fluidity like this. It isn't intended that collections would be created dynamically. But it's interesting it kinda works :)

In theory this should be ok as long as the list of podcasts doesn't change, as the config is only generated at app startup, so new podcasts wouldn't get picked up till the next app recycle.

Fluidity doesn't yet have the concept of collections in collections (there is actually an open issue about this, see #41 and feel free to add your feedback). The suggested approach for now would be to manage the podcasts and episodes seperately and then maybe use a data views builder to created filtered lists of episodes (probably not ideal, but it's what we go at the moment).

Then, because podcasts are also now a collection, from within the episode editor you can create a fluidity entity picker property editor to pick a parent podcast and this gives you your parent linkage.

**Comment by mattbrailsford** [comment]
Discussed this issue outside of GitHub and found an adequate workaround. The ultimate problem is that of child collection which we already have an issue for #41 so I'm closing this issue down.
